--drop table Operations 
--drop table Stock
--drop table Materials 
--drop table RoleRights 

--drop table UserRights 
--drop table Users 
--drop table UserRole 
--drop table Persons 
--drop table Currencies 
--drop table TypeOfMaterial 
--drop table TypeOfMesure 